# Generated by Django 5.1.5 on 2026-03-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_name', models.CharField(max_length=200)),
                ('date_revservation', models.DateTimeField(unique=True)),
                ('email_client', models.EmailField(max_length=254)),
            ],
        ),
    ]
