name: Deploy React (Frontend)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4 # Version optimisée

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Installer les dépendances
        working-directory: ./frontend
        run: npm ci # 'npm ci' est plus propre et rapide que 'npm install' en CI/CD
        
      - name: Builder l'application React
        working-directory: ./frontend
        run: npm run build

      - name: Sauvegarder les fichiers buildés
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/

        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Télécharger l'artifact buildé
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: frontend/build/
          
      - name: Déployer vers LWS
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{secrets.FTP_SERVER}}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: frontend/build/
          server-dir: ${{secrets.FTP_FRONTEND_PATH}}
