# name: Deploy React (Frontend)
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'frontend/**' # Déclencheur magique : surveille uniquement ce dossier

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Forcer le redémarrage de l'app sur LWS
#         working-directory: ./backend
#         run: |
#           mkdir -p tmp
#           touch tmp/restart.txt

#       - name: Récupérer le code
#         uses: actions/checkout@v4 # Version optimisée

#       - name: Installer Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: 18
#           cache: 'npm'
#           cache-dependency-path: frontend/package-lock.json

#       - name: Installer les dépendances
#         working-directory: ./frontend
#         run: npm ci # 'npm ci' est plus propre et rapide que 'npm install' en CI/CD

#       - name: Builder l'application React
#         working-directory: ./frontend
#         run: npm run build

#       - name: Déployer vers LWS (Dossier /www)
#         uses: SamKirkland/FTP-Deploy-Action@v4.3.4
#         with:
#           server: ftp.tonsite.com
#           username: ${{ secrets.FTP_USERNAME }}
#           password: ${{ secrets.FTP_PASSWORD }}
#           local-dir: frontend/build/
#           server-dir: /www/
